project:
  type: website
  output-dir: docs
  resources:
    - "data/**"
website:
  title: "Portefolio Pierre Chauvet"
  navbar:
    background: primary 
    left:
      - text: "Accueil"
        href: index.qmd
      - text: "Images réalistes"
        href: img_realiste.qmd
      - text: "Scène 3D"
        href: opengl.qmd
      - text: "Génération de monde"
        href: generation_monde.qmd
      - text: "Projet SIRI"
        href: siri.qmd

format:
  html:
    theme: cosmo
    css: site.css
    page-layout: full